String.toLocaleString({
    "en-US": {
        "%level": "Level",
        "%score": "Score",
        "%rows": "Rows",
        "%record": "Record",
        "%paused": "Paused",
        "%about": "About",
        "%developed-by": "developed by RobertoPC",
        "%soundfx-by": "SoundFX by",
        "%like-it": "Like it?",
        "%keep-a-review": "Keep a review",
        "%here": "here",
        "%version": "version "+ window.version,
        "%game-over": "Game Over",
        "%new-record": "New Record",
        "%wish-start-a-new-game": "Wish start a new game?",
        "%yes": "Yes",
        "%no": "No",
        "%use-keyboard-to-play": "Use keyboard to play",
        "%move-left": "left",
        "%move-right": "right",
        "%or": "or",
        "%to-rotate": "rotate",
        "%move-down": "down",
        "%next": "Next",
        "%repository": "Repository"
    },
    "pt-BR": {
        "%level": "Nivel",
        "%score": "Pontos",
        "%rows": "Linhas",
        "%record": "Recorde",
        "%paused": "Pausado",
        "%about": "Sobre",
        "%developed-by": "desenvolvido por RobertoPC",
        "%soundfx-by": "Sons por",
        "%like-it": "Gostou?",
        "%keep-a-review": "Deixe um review",
        "%here": "aqui",
        "%version": "versão "+ window.version,
        "%game-over": "Fim do Jogo",
        "%new-record": "Novo Recorde",
        "%wish-start-a-new-game": "Deseja iniciar um novo jogo?",
        "%yes": "Sim",
        "%no": "Não",
        "%use-keyboard-to-play": "Use o teclado para jogar",
        "%move-left": "esquerda",
        "%move-right": "direita",
        "%or": "ou",
        "%to-rotate": "rodar",
        "%move-down": "desce",
        "%next": "Próxima",
        "%repository": "Repositório"
    },
    "es": {
        "%level": "Nivel",
        "%score": "Resultado",
        "%rows": "Filas",
        "%record": "Registro",
        "%paused": "Pausa",
        "%about": "Acerca",
        "%developed-by": "desarrolladas por RobertoPC",
        "%soundfx-by": "SoundFX por",
        "%like-it": "¿Te gusta?",
        "%keep-a-review": "Mantenga una opinión",
        "%here": "aquí",
        "%version": "versión "+ window.version,
        "%game-over": "Fin del Juego",
        "%new-record": "Nuevo registro",
        "%wish-start-a-new-game": "¿Comenzar un nuevo juego?",
        "%yes": "Sí",
        "%no": "No",
        "%use-keyboard-to-play": "Uso del teclado para jugar",
        "%move-left": "izquierda",
        "%move-right": "derecha",
        "%or": "o",
        "%to-rotate": "girar",
        "%move-down": "abajo",
        "%next": "Siguiente",
        "%repository": "Repositório"
    }
});
